spring.application.name=api
spring.data.mongodb.uri=mongodb+srv://parshwajust55_db_user:Pa30%402005@cluster0.3wzwtqy.mongodb.net/invoice_db?appName=Cluster0
spring.mongodb.uri=mongodb+srv://parshwajust55_db_user:Pa30%402005@cluster0.3wzwtqy.mongodb.net/invoice_db?appName=Cluster0
spring.data.mongodb.host=cluster0.3wzwtqy.mongodb.net

# Dummy email configuration to satisfy JavaMailSender
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your_email@gmail.com
spring.mail.password=your_app_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true